TOPDIR ?= ../..
BLACKLIST := \
	sun4i-a10-inet97fv2 \
	rk3288-veyron-brain \
	rk3288-veyron-mickey \
	imx6qp-nitrogen6_max \
	imx6qp-nitrogen6_som2 \
	imx6qp-sabreauto \
	bcm21664-garnet \
	bcm23550-sparrow \
	bcm2837-rpi-3-b \
	exynos3250-monk \
	exynos4412-trats2 \
	exynos3250-rinato

BOARDS := $(shell ls *.dts)
include $(TOPDIR)/test-suite/Makefile.inc
