TOPDIR ?= ../..
BLACKLIST := sun4i-a10-inet97fv2 bcm21664-garnet bcm23550-sparrow exynos3250-monk exynos4412-trats2 exynos3250-rinato

BOARDS := $(shell ls *.dts)
include $(TOPDIR)/test-suite/Makefile.inc
