TOPDIR ?= ../../..
BLACKLIST := sun50i-h5-orangepi-zero-plus2 sun50i-h5-nanopi-neo2 sun50i-h5-orangepi-pc2 sun50i-h5-orangepi-prime

BOARDS := $(shell ls *.dts)
include $(TOPDIR)/test-suite/Makefile.inc
